service: pull-requests-reminder

custom:
  defaultRegion: 'us-east-1'
  defaultStage: dev

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}

functions:
  remind:
    handler: src/index.remind
    events:
      - schedule: ${opt:schedule}
    environment:
      SLACK_CHANNEL: ${opt:slack-channel}
      SLACK_TOKEN: ${opt:slack-token}
      DEFAULT_OWNER: ${opt:default-owner}
      REPOSITORIES: ${opt:repos}
      GIT_PERSONAL_ACCESS_TOKEN: ${opt:git-pat}
      IGNORE_WORDS: ${opt:ignore-words}
      IGNORE_LABELS: ${opt:ignore-labels}
      ALWAYS_APPENDED_TEXT: ${opt:append-text}

