service: pull-requests-reminder

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, dev}
  region: ${opt:region, us-east-1}

  functions:
    remind:
      handler: src/index.remind
      events:
        - schedule: ${opt:schedule}
          environment:
            SLACK_CHANNEL: ${opt:slack-channel}
            SLACK_HOOK: ${opt:slack-hook}
            DEFAULT_OWNER: ${opt:default-owner}
            REPOSITORIES: ${opt:repos}
            GIT_PERSONAL_ACCESS_TOKEN: ${opt:git-pat}

